// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePack) DeepCopyInto(out *ConfigOrganizationConformancePack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePack.
func (in *ConfigOrganizationConformancePack) DeepCopy() *ConfigOrganizationConformancePack {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigOrganizationConformancePack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePackList) DeepCopyInto(out *ConfigOrganizationConformancePackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigOrganizationConformancePack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePackList.
func (in *ConfigOrganizationConformancePackList) DeepCopy() *ConfigOrganizationConformancePackList {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigOrganizationConformancePackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePackObservation) DeepCopyInto(out *ConfigOrganizationConformancePackObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePackObservation.
func (in *ConfigOrganizationConformancePackObservation) DeepCopy() *ConfigOrganizationConformancePackObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePackObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePackParameters) DeepCopyInto(out *ConfigOrganizationConformancePackParameters) {
	*out = *in
	if in.DeliveryS3Bucket != nil {
		in, out := &in.DeliveryS3Bucket, &out.DeliveryS3Bucket
		*out = new(string)
		**out = **in
	}
	if in.DeliveryS3KeyPrefix != nil {
		in, out := &in.DeliveryS3KeyPrefix, &out.DeliveryS3KeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.ExcludedAccounts != nil {
		in, out := &in.ExcludedAccounts, &out.ExcludedAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputParameter != nil {
		in, out := &in.InputParameter, &out.InputParameter
		*out = make([]InputParameterParameters, len(*in))
		copy(*out, *in)
	}
	if in.TemplateBody != nil {
		in, out := &in.TemplateBody, &out.TemplateBody
		*out = new(string)
		**out = **in
	}
	if in.TemplateS3Uri != nil {
		in, out := &in.TemplateS3Uri, &out.TemplateS3Uri
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePackParameters.
func (in *ConfigOrganizationConformancePackParameters) DeepCopy() *ConfigOrganizationConformancePackParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePackParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePackSpec) DeepCopyInto(out *ConfigOrganizationConformancePackSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePackSpec.
func (in *ConfigOrganizationConformancePackSpec) DeepCopy() *ConfigOrganizationConformancePackSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOrganizationConformancePackStatus) DeepCopyInto(out *ConfigOrganizationConformancePackStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOrganizationConformancePackStatus.
func (in *ConfigOrganizationConformancePackStatus) DeepCopy() *ConfigOrganizationConformancePackStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigOrganizationConformancePackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputParameterObservation) DeepCopyInto(out *InputParameterObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputParameterObservation.
func (in *InputParameterObservation) DeepCopy() *InputParameterObservation {
	if in == nil {
		return nil
	}
	out := new(InputParameterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputParameterParameters) DeepCopyInto(out *InputParameterParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputParameterParameters.
func (in *InputParameterParameters) DeepCopy() *InputParameterParameters {
	if in == nil {
		return nil
	}
	out := new(InputParameterParameters)
	in.DeepCopyInto(out)
	return out
}
