/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=ec2.aws.tf.crossplane.io
// +versionName=v1alpha1

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1alpha1 "github.com/crossplane-contrib/provider-tf-aws/apis/ec2/v1alpha1"
)

type Ec2TrafficMirrorSessionObservation struct {
	Arn string `json:"arn" tf:"arn"`

	OwnerId string `json:"ownerId" tf:"owner_id"`
}

type Ec2TrafficMirrorSessionParameters struct {
	Description *string `json:"description,omitempty" tf:"description"`

	NetworkInterfaceId string `json:"networkInterfaceId" tf:"network_interface_id"`

	PacketLength *int64 `json:"packetLength,omitempty" tf:"packet_length"`

	SessionNumber int64 `json:"sessionNumber" tf:"session_number"`

	Tags map[string]string `json:"tags,omitempty" tf:"tags"`

	TagsAll map[string]string `json:"tagsAll,omitempty" tf:"tags_all"`

	TrafficMirrorFilterId string `json:"trafficMirrorFilterId" tf:"traffic_mirror_filter_id"`

	TrafficMirrorTargetId string `json:"trafficMirrorTargetId" tf:"traffic_mirror_target_id"`

	VirtualNetworkId *int64 `json:"virtualNetworkId,omitempty" tf:"virtual_network_id"`
}

// Ec2TrafficMirrorSessionSpec defines the desired state of Ec2TrafficMirrorSession
type Ec2TrafficMirrorSessionSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       Ec2TrafficMirrorSessionParameters `json:"forProvider"`
}

// Ec2TrafficMirrorSessionStatus defines the observed state of Ec2TrafficMirrorSession.
type Ec2TrafficMirrorSessionStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          Ec2TrafficMirrorSessionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Ec2TrafficMirrorSession is the Schema for the Ec2TrafficMirrorSessions API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type Ec2TrafficMirrorSession struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              Ec2TrafficMirrorSessionSpec   `json:"spec"`
	Status            Ec2TrafficMirrorSessionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// Ec2TrafficMirrorSessionList contains a list of Ec2TrafficMirrorSessions
type Ec2TrafficMirrorSessionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ec2TrafficMirrorSession `json:"items"`
}

// Repository type metadata.
var (
	Ec2TrafficMirrorSessionKind             = "Ec2TrafficMirrorSession"
	Ec2TrafficMirrorSessionGroupKind        = schema.GroupKind{Group: v1alpha1.Group, Kind: Ec2TrafficMirrorSessionKind}.String()
	Ec2TrafficMirrorSessionKindAPIVersion   = Ec2TrafficMirrorSessionKind + "." + v1alpha1.GroupVersion.String()
	Ec2TrafficMirrorSessionGroupVersionKind = v1alpha1.GroupVersion.WithKind(Ec2TrafficMirrorSessionKind)
)

func init() {
	v1alpha1.SchemeBuilder.Register(&Ec2TrafficMirrorSession{}, &Ec2TrafficMirrorSessionList{})
}
