/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BucketPolicyObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BucketPolicyParameters struct {

	// +kubebuilder:validation:Required
	Bucket *string `json:"bucket" tf:"bucket,omitempty"`

	// +kubebuilder:validation:Required
	Policy *string `json:"policy" tf:"policy,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +terrajet:crd:field:TFTag=-
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"-"`
}

// BucketPolicySpec defines the desired state of BucketPolicy
type BucketPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BucketPolicyParameters `json:"forProvider"`
}

// BucketPolicyStatus defines the observed state of BucketPolicy.
type BucketPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BucketPolicy is the Schema for the BucketPolicys API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,awsjet}
type BucketPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BucketPolicySpec   `json:"spec"`
	Status            BucketPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketPolicyList contains a list of BucketPolicys
type BucketPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketPolicy `json:"items"`
}

// Repository type metadata.
var (
	BucketPolicy_Kind             = "BucketPolicy"
	BucketPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketPolicy_Kind}.String()
	BucketPolicy_KindAPIVersion   = BucketPolicy_Kind + "." + CRDGroupVersion.String()
	BucketPolicy_GroupVersionKind = CRDGroupVersion.WithKind(BucketPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketPolicy{}, &BucketPolicyList{})
}
