// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociation) DeepCopyInto(out *Route53ResolverRuleAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociation.
func (in *Route53ResolverRuleAssociation) DeepCopy() *Route53ResolverRuleAssociation {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Route53ResolverRuleAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociationList) DeepCopyInto(out *Route53ResolverRuleAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Route53ResolverRuleAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociationList.
func (in *Route53ResolverRuleAssociationList) DeepCopy() *Route53ResolverRuleAssociationList {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Route53ResolverRuleAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociationObservation) DeepCopyInto(out *Route53ResolverRuleAssociationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociationObservation.
func (in *Route53ResolverRuleAssociationObservation) DeepCopy() *Route53ResolverRuleAssociationObservation {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociationParameters) DeepCopyInto(out *Route53ResolverRuleAssociationParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociationParameters.
func (in *Route53ResolverRuleAssociationParameters) DeepCopy() *Route53ResolverRuleAssociationParameters {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociationSpec) DeepCopyInto(out *Route53ResolverRuleAssociationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociationSpec.
func (in *Route53ResolverRuleAssociationSpec) DeepCopy() *Route53ResolverRuleAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ResolverRuleAssociationStatus) DeepCopyInto(out *Route53ResolverRuleAssociationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ResolverRuleAssociationStatus.
func (in *Route53ResolverRuleAssociationStatus) DeepCopy() *Route53ResolverRuleAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(Route53ResolverRuleAssociationStatus)
	in.DeepCopyInto(out)
	return out
}
