// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionObservation) DeepCopyInto(out *ActionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionObservation.
func (in *ActionObservation) DeepCopy() *ActionObservation {
	if in == nil {
		return nil
	}
	out := new(ActionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionParameters) DeepCopyInto(out *ActionParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]AllowParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]BlockParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = make([]CountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionParameters.
func (in *ActionParameters) DeepCopy() *ActionParameters {
	if in == nil {
		return nil
	}
	out := new(ActionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllQueryArgumentsObservation) DeepCopyInto(out *AllQueryArgumentsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllQueryArgumentsObservation.
func (in *AllQueryArgumentsObservation) DeepCopy() *AllQueryArgumentsObservation {
	if in == nil {
		return nil
	}
	out := new(AllQueryArgumentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllQueryArgumentsParameters) DeepCopyInto(out *AllQueryArgumentsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllQueryArgumentsParameters.
func (in *AllQueryArgumentsParameters) DeepCopy() *AllQueryArgumentsParameters {
	if in == nil {
		return nil
	}
	out := new(AllQueryArgumentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowObservation) DeepCopyInto(out *AllowObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowObservation.
func (in *AllowObservation) DeepCopy() *AllowObservation {
	if in == nil {
		return nil
	}
	out := new(AllowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowParameters) DeepCopyInto(out *AllowParameters) {
	*out = *in
	if in.CustomRequestHandling != nil {
		in, out := &in.CustomRequestHandling, &out.CustomRequestHandling
		*out = make([]CustomRequestHandlingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowParameters.
func (in *AllowParameters) DeepCopy() *AllowParameters {
	if in == nil {
		return nil
	}
	out := new(AllowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AndStatementObservation) DeepCopyInto(out *AndStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AndStatementObservation.
func (in *AndStatementObservation) DeepCopy() *AndStatementObservation {
	if in == nil {
		return nil
	}
	out := new(AndStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AndStatementParameters) DeepCopyInto(out *AndStatementParameters) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]StatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AndStatementParameters.
func (in *AndStatementParameters) DeepCopy() *AndStatementParameters {
	if in == nil {
		return nil
	}
	out := new(AndStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockObservation) DeepCopyInto(out *BlockObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockObservation.
func (in *BlockObservation) DeepCopy() *BlockObservation {
	if in == nil {
		return nil
	}
	out := new(BlockObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockParameters) DeepCopyInto(out *BlockParameters) {
	*out = *in
	if in.CustomResponse != nil {
		in, out := &in.CustomResponse, &out.CustomResponse
		*out = make([]CustomResponseParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockParameters.
func (in *BlockParameters) DeepCopy() *BlockParameters {
	if in == nil {
		return nil
	}
	out := new(BlockParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyObservation) DeepCopyInto(out *BodyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyObservation.
func (in *BodyObservation) DeepCopy() *BodyObservation {
	if in == nil {
		return nil
	}
	out := new(BodyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyParameters) DeepCopyInto(out *BodyParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyParameters.
func (in *BodyParameters) DeepCopy() *BodyParameters {
	if in == nil {
		return nil
	}
	out := new(BodyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchStatementObservation) DeepCopyInto(out *ByteMatchStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchStatementObservation.
func (in *ByteMatchStatementObservation) DeepCopy() *ByteMatchStatementObservation {
	if in == nil {
		return nil
	}
	out := new(ByteMatchStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchStatementParameters) DeepCopyInto(out *ByteMatchStatementParameters) {
	*out = *in
	if in.FieldToMatch != nil {
		in, out := &in.FieldToMatch, &out.FieldToMatch
		*out = make([]FieldToMatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextTransformation != nil {
		in, out := &in.TextTransformation, &out.TextTransformation
		*out = make([]TextTransformationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchStatementParameters.
func (in *ByteMatchStatementParameters) DeepCopy() *ByteMatchStatementParameters {
	if in == nil {
		return nil
	}
	out := new(ByteMatchStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountObservation) DeepCopyInto(out *CountObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountObservation.
func (in *CountObservation) DeepCopy() *CountObservation {
	if in == nil {
		return nil
	}
	out := new(CountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountParameters) DeepCopyInto(out *CountParameters) {
	*out = *in
	if in.CustomRequestHandling != nil {
		in, out := &in.CustomRequestHandling, &out.CustomRequestHandling
		*out = make([]CustomRequestHandlingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountParameters.
func (in *CountParameters) DeepCopy() *CountParameters {
	if in == nil {
		return nil
	}
	out := new(CountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomRequestHandlingObservation) DeepCopyInto(out *CustomRequestHandlingObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomRequestHandlingObservation.
func (in *CustomRequestHandlingObservation) DeepCopy() *CustomRequestHandlingObservation {
	if in == nil {
		return nil
	}
	out := new(CustomRequestHandlingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomRequestHandlingParameters) DeepCopyInto(out *CustomRequestHandlingParameters) {
	*out = *in
	if in.InsertHeader != nil {
		in, out := &in.InsertHeader, &out.InsertHeader
		*out = make([]InsertHeaderParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomRequestHandlingParameters.
func (in *CustomRequestHandlingParameters) DeepCopy() *CustomRequestHandlingParameters {
	if in == nil {
		return nil
	}
	out := new(CustomRequestHandlingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResponseObservation) DeepCopyInto(out *CustomResponseObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResponseObservation.
func (in *CustomResponseObservation) DeepCopy() *CustomResponseObservation {
	if in == nil {
		return nil
	}
	out := new(CustomResponseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResponseParameters) DeepCopyInto(out *CustomResponseParameters) {
	*out = *in
	if in.ResponseHeader != nil {
		in, out := &in.ResponseHeader, &out.ResponseHeader
		*out = make([]ResponseHeaderParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResponseParameters.
func (in *CustomResponseParameters) DeepCopy() *CustomResponseParameters {
	if in == nil {
		return nil
	}
	out := new(CustomResponseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultActionObservation) DeepCopyInto(out *DefaultActionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultActionObservation.
func (in *DefaultActionObservation) DeepCopy() *DefaultActionObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultActionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultActionParameters) DeepCopyInto(out *DefaultActionParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]AllowParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]BlockParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultActionParameters.
func (in *DefaultActionParameters) DeepCopy() *DefaultActionParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultActionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludedRuleObservation) DeepCopyInto(out *ExcludedRuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludedRuleObservation.
func (in *ExcludedRuleObservation) DeepCopy() *ExcludedRuleObservation {
	if in == nil {
		return nil
	}
	out := new(ExcludedRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludedRuleParameters) DeepCopyInto(out *ExcludedRuleParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludedRuleParameters.
func (in *ExcludedRuleParameters) DeepCopy() *ExcludedRuleParameters {
	if in == nil {
		return nil
	}
	out := new(ExcludedRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldToMatchObservation) DeepCopyInto(out *FieldToMatchObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldToMatchObservation.
func (in *FieldToMatchObservation) DeepCopy() *FieldToMatchObservation {
	if in == nil {
		return nil
	}
	out := new(FieldToMatchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldToMatchParameters) DeepCopyInto(out *FieldToMatchParameters) {
	*out = *in
	if in.AllQueryArguments != nil {
		in, out := &in.AllQueryArguments, &out.AllQueryArguments
		*out = make([]AllQueryArgumentsParameters, len(*in))
		copy(*out, *in)
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = make([]BodyParameters, len(*in))
		copy(*out, *in)
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = make([]MethodParameters, len(*in))
		copy(*out, *in)
	}
	if in.QueryString != nil {
		in, out := &in.QueryString, &out.QueryString
		*out = make([]QueryStringParameters, len(*in))
		copy(*out, *in)
	}
	if in.SingleHeader != nil {
		in, out := &in.SingleHeader, &out.SingleHeader
		*out = make([]SingleHeaderParameters, len(*in))
		copy(*out, *in)
	}
	if in.SingleQueryArgument != nil {
		in, out := &in.SingleQueryArgument, &out.SingleQueryArgument
		*out = make([]SingleQueryArgumentParameters, len(*in))
		copy(*out, *in)
	}
	if in.UriPath != nil {
		in, out := &in.UriPath, &out.UriPath
		*out = make([]UriPathParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldToMatchParameters.
func (in *FieldToMatchParameters) DeepCopy() *FieldToMatchParameters {
	if in == nil {
		return nil
	}
	out := new(FieldToMatchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardedIpConfigObservation) DeepCopyInto(out *ForwardedIpConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardedIpConfigObservation.
func (in *ForwardedIpConfigObservation) DeepCopy() *ForwardedIpConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ForwardedIpConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardedIpConfigParameters) DeepCopyInto(out *ForwardedIpConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardedIpConfigParameters.
func (in *ForwardedIpConfigParameters) DeepCopy() *ForwardedIpConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ForwardedIpConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoMatchStatementObservation) DeepCopyInto(out *GeoMatchStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoMatchStatementObservation.
func (in *GeoMatchStatementObservation) DeepCopy() *GeoMatchStatementObservation {
	if in == nil {
		return nil
	}
	out := new(GeoMatchStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoMatchStatementParameters) DeepCopyInto(out *GeoMatchStatementParameters) {
	*out = *in
	if in.CountryCodes != nil {
		in, out := &in.CountryCodes, &out.CountryCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForwardedIpConfig != nil {
		in, out := &in.ForwardedIpConfig, &out.ForwardedIpConfig
		*out = make([]ForwardedIpConfigParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoMatchStatementParameters.
func (in *GeoMatchStatementParameters) DeepCopy() *GeoMatchStatementParameters {
	if in == nil {
		return nil
	}
	out := new(GeoMatchStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsertHeaderObservation) DeepCopyInto(out *InsertHeaderObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsertHeaderObservation.
func (in *InsertHeaderObservation) DeepCopy() *InsertHeaderObservation {
	if in == nil {
		return nil
	}
	out := new(InsertHeaderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsertHeaderParameters) DeepCopyInto(out *InsertHeaderParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsertHeaderParameters.
func (in *InsertHeaderParameters) DeepCopy() *InsertHeaderParameters {
	if in == nil {
		return nil
	}
	out := new(InsertHeaderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpSetForwardedIpConfigObservation) DeepCopyInto(out *IpSetForwardedIpConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetForwardedIpConfigObservation.
func (in *IpSetForwardedIpConfigObservation) DeepCopy() *IpSetForwardedIpConfigObservation {
	if in == nil {
		return nil
	}
	out := new(IpSetForwardedIpConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpSetForwardedIpConfigParameters) DeepCopyInto(out *IpSetForwardedIpConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetForwardedIpConfigParameters.
func (in *IpSetForwardedIpConfigParameters) DeepCopy() *IpSetForwardedIpConfigParameters {
	if in == nil {
		return nil
	}
	out := new(IpSetForwardedIpConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpSetReferenceStatementObservation) DeepCopyInto(out *IpSetReferenceStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetReferenceStatementObservation.
func (in *IpSetReferenceStatementObservation) DeepCopy() *IpSetReferenceStatementObservation {
	if in == nil {
		return nil
	}
	out := new(IpSetReferenceStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpSetReferenceStatementParameters) DeepCopyInto(out *IpSetReferenceStatementParameters) {
	*out = *in
	if in.IpSetForwardedIpConfig != nil {
		in, out := &in.IpSetForwardedIpConfig, &out.IpSetForwardedIpConfig
		*out = make([]IpSetForwardedIpConfigParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetReferenceStatementParameters.
func (in *IpSetReferenceStatementParameters) DeepCopy() *IpSetReferenceStatementParameters {
	if in == nil {
		return nil
	}
	out := new(IpSetReferenceStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRuleGroupStatementObservation) DeepCopyInto(out *ManagedRuleGroupStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRuleGroupStatementObservation.
func (in *ManagedRuleGroupStatementObservation) DeepCopy() *ManagedRuleGroupStatementObservation {
	if in == nil {
		return nil
	}
	out := new(ManagedRuleGroupStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRuleGroupStatementParameters) DeepCopyInto(out *ManagedRuleGroupStatementParameters) {
	*out = *in
	if in.ExcludedRule != nil {
		in, out := &in.ExcludedRule, &out.ExcludedRule
		*out = make([]ExcludedRuleParameters, len(*in))
		copy(*out, *in)
	}
	if in.ScopeDownStatement != nil {
		in, out := &in.ScopeDownStatement, &out.ScopeDownStatement
		*out = make([]ScopeDownStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRuleGroupStatementParameters.
func (in *ManagedRuleGroupStatementParameters) DeepCopy() *ManagedRuleGroupStatementParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedRuleGroupStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodObservation) DeepCopyInto(out *MethodObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodObservation.
func (in *MethodObservation) DeepCopy() *MethodObservation {
	if in == nil {
		return nil
	}
	out := new(MethodObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodParameters) DeepCopyInto(out *MethodParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodParameters.
func (in *MethodParameters) DeepCopy() *MethodParameters {
	if in == nil {
		return nil
	}
	out := new(MethodParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoneObservation) DeepCopyInto(out *NoneObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoneObservation.
func (in *NoneObservation) DeepCopy() *NoneObservation {
	if in == nil {
		return nil
	}
	out := new(NoneObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoneParameters) DeepCopyInto(out *NoneParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoneParameters.
func (in *NoneParameters) DeepCopy() *NoneParameters {
	if in == nil {
		return nil
	}
	out := new(NoneParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotStatementObservation) DeepCopyInto(out *NotStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotStatementObservation.
func (in *NotStatementObservation) DeepCopy() *NotStatementObservation {
	if in == nil {
		return nil
	}
	out := new(NotStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotStatementParameters) DeepCopyInto(out *NotStatementParameters) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]StatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotStatementParameters.
func (in *NotStatementParameters) DeepCopy() *NotStatementParameters {
	if in == nil {
		return nil
	}
	out := new(NotStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrStatementObservation) DeepCopyInto(out *OrStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrStatementObservation.
func (in *OrStatementObservation) DeepCopy() *OrStatementObservation {
	if in == nil {
		return nil
	}
	out := new(OrStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrStatementParameters) DeepCopyInto(out *OrStatementParameters) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]StatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrStatementParameters.
func (in *OrStatementParameters) DeepCopy() *OrStatementParameters {
	if in == nil {
		return nil
	}
	out := new(OrStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideActionObservation) DeepCopyInto(out *OverrideActionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideActionObservation.
func (in *OverrideActionObservation) DeepCopy() *OverrideActionObservation {
	if in == nil {
		return nil
	}
	out := new(OverrideActionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideActionParameters) DeepCopyInto(out *OverrideActionParameters) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = make([]CountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.None != nil {
		in, out := &in.None, &out.None
		*out = make([]NoneParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideActionParameters.
func (in *OverrideActionParameters) DeepCopy() *OverrideActionParameters {
	if in == nil {
		return nil
	}
	out := new(OverrideActionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryStringObservation) DeepCopyInto(out *QueryStringObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryStringObservation.
func (in *QueryStringObservation) DeepCopy() *QueryStringObservation {
	if in == nil {
		return nil
	}
	out := new(QueryStringObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryStringParameters) DeepCopyInto(out *QueryStringParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryStringParameters.
func (in *QueryStringParameters) DeepCopy() *QueryStringParameters {
	if in == nil {
		return nil
	}
	out := new(QueryStringParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateBasedStatementObservation) DeepCopyInto(out *RateBasedStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateBasedStatementObservation.
func (in *RateBasedStatementObservation) DeepCopy() *RateBasedStatementObservation {
	if in == nil {
		return nil
	}
	out := new(RateBasedStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateBasedStatementParameters) DeepCopyInto(out *RateBasedStatementParameters) {
	*out = *in
	if in.AggregateKeyType != nil {
		in, out := &in.AggregateKeyType, &out.AggregateKeyType
		*out = new(string)
		**out = **in
	}
	if in.ForwardedIpConfig != nil {
		in, out := &in.ForwardedIpConfig, &out.ForwardedIpConfig
		*out = make([]ForwardedIpConfigParameters, len(*in))
		copy(*out, *in)
	}
	if in.ScopeDownStatement != nil {
		in, out := &in.ScopeDownStatement, &out.ScopeDownStatement
		*out = make([]ScopeDownStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateBasedStatementParameters.
func (in *RateBasedStatementParameters) DeepCopy() *RateBasedStatementParameters {
	if in == nil {
		return nil
	}
	out := new(RateBasedStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegexPatternSetReferenceStatementObservation) DeepCopyInto(out *RegexPatternSetReferenceStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegexPatternSetReferenceStatementObservation.
func (in *RegexPatternSetReferenceStatementObservation) DeepCopy() *RegexPatternSetReferenceStatementObservation {
	if in == nil {
		return nil
	}
	out := new(RegexPatternSetReferenceStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegexPatternSetReferenceStatementParameters) DeepCopyInto(out *RegexPatternSetReferenceStatementParameters) {
	*out = *in
	if in.FieldToMatch != nil {
		in, out := &in.FieldToMatch, &out.FieldToMatch
		*out = make([]FieldToMatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextTransformation != nil {
		in, out := &in.TextTransformation, &out.TextTransformation
		*out = make([]TextTransformationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegexPatternSetReferenceStatementParameters.
func (in *RegexPatternSetReferenceStatementParameters) DeepCopy() *RegexPatternSetReferenceStatementParameters {
	if in == nil {
		return nil
	}
	out := new(RegexPatternSetReferenceStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseHeaderObservation) DeepCopyInto(out *ResponseHeaderObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseHeaderObservation.
func (in *ResponseHeaderObservation) DeepCopy() *ResponseHeaderObservation {
	if in == nil {
		return nil
	}
	out := new(ResponseHeaderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseHeaderParameters) DeepCopyInto(out *ResponseHeaderParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseHeaderParameters.
func (in *ResponseHeaderParameters) DeepCopy() *ResponseHeaderParameters {
	if in == nil {
		return nil
	}
	out := new(ResponseHeaderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupReferenceStatementObservation) DeepCopyInto(out *RuleGroupReferenceStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupReferenceStatementObservation.
func (in *RuleGroupReferenceStatementObservation) DeepCopy() *RuleGroupReferenceStatementObservation {
	if in == nil {
		return nil
	}
	out := new(RuleGroupReferenceStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupReferenceStatementParameters) DeepCopyInto(out *RuleGroupReferenceStatementParameters) {
	*out = *in
	if in.ExcludedRule != nil {
		in, out := &in.ExcludedRule, &out.ExcludedRule
		*out = make([]ExcludedRuleParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupReferenceStatementParameters.
func (in *RuleGroupReferenceStatementParameters) DeepCopy() *RuleGroupReferenceStatementParameters {
	if in == nil {
		return nil
	}
	out := new(RuleGroupReferenceStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleObservation) DeepCopyInto(out *RuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleObservation.
func (in *RuleObservation) DeepCopy() *RuleObservation {
	if in == nil {
		return nil
	}
	out := new(RuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParameters) DeepCopyInto(out *RuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make([]ActionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OverrideAction != nil {
		in, out := &in.OverrideAction, &out.OverrideAction
		*out = make([]OverrideActionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]StatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VisibilityConfig != nil {
		in, out := &in.VisibilityConfig, &out.VisibilityConfig
		*out = make([]VisibilityConfigParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParameters.
func (in *RuleParameters) DeepCopy() *RuleParameters {
	if in == nil {
		return nil
	}
	out := new(RuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeDownStatementObservation) DeepCopyInto(out *ScopeDownStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeDownStatementObservation.
func (in *ScopeDownStatementObservation) DeepCopy() *ScopeDownStatementObservation {
	if in == nil {
		return nil
	}
	out := new(ScopeDownStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeDownStatementParameters) DeepCopyInto(out *ScopeDownStatementParameters) {
	*out = *in
	if in.AndStatement != nil {
		in, out := &in.AndStatement, &out.AndStatement
		*out = make([]AndStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ByteMatchStatement != nil {
		in, out := &in.ByteMatchStatement, &out.ByteMatchStatement
		*out = make([]ByteMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GeoMatchStatement != nil {
		in, out := &in.GeoMatchStatement, &out.GeoMatchStatement
		*out = make([]GeoMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IpSetReferenceStatement != nil {
		in, out := &in.IpSetReferenceStatement, &out.IpSetReferenceStatement
		*out = make([]IpSetReferenceStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotStatement != nil {
		in, out := &in.NotStatement, &out.NotStatement
		*out = make([]NotStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OrStatement != nil {
		in, out := &in.OrStatement, &out.OrStatement
		*out = make([]OrStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegexPatternSetReferenceStatement != nil {
		in, out := &in.RegexPatternSetReferenceStatement, &out.RegexPatternSetReferenceStatement
		*out = make([]RegexPatternSetReferenceStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SizeConstraintStatement != nil {
		in, out := &in.SizeConstraintStatement, &out.SizeConstraintStatement
		*out = make([]SizeConstraintStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SqliMatchStatement != nil {
		in, out := &in.SqliMatchStatement, &out.SqliMatchStatement
		*out = make([]SqliMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.XssMatchStatement != nil {
		in, out := &in.XssMatchStatement, &out.XssMatchStatement
		*out = make([]XssMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeDownStatementParameters.
func (in *ScopeDownStatementParameters) DeepCopy() *ScopeDownStatementParameters {
	if in == nil {
		return nil
	}
	out := new(ScopeDownStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleHeaderObservation) DeepCopyInto(out *SingleHeaderObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleHeaderObservation.
func (in *SingleHeaderObservation) DeepCopy() *SingleHeaderObservation {
	if in == nil {
		return nil
	}
	out := new(SingleHeaderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleHeaderParameters) DeepCopyInto(out *SingleHeaderParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleHeaderParameters.
func (in *SingleHeaderParameters) DeepCopy() *SingleHeaderParameters {
	if in == nil {
		return nil
	}
	out := new(SingleHeaderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleQueryArgumentObservation) DeepCopyInto(out *SingleQueryArgumentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleQueryArgumentObservation.
func (in *SingleQueryArgumentObservation) DeepCopy() *SingleQueryArgumentObservation {
	if in == nil {
		return nil
	}
	out := new(SingleQueryArgumentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleQueryArgumentParameters) DeepCopyInto(out *SingleQueryArgumentParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleQueryArgumentParameters.
func (in *SingleQueryArgumentParameters) DeepCopy() *SingleQueryArgumentParameters {
	if in == nil {
		return nil
	}
	out := new(SingleQueryArgumentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintStatementObservation) DeepCopyInto(out *SizeConstraintStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintStatementObservation.
func (in *SizeConstraintStatementObservation) DeepCopy() *SizeConstraintStatementObservation {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintStatementParameters) DeepCopyInto(out *SizeConstraintStatementParameters) {
	*out = *in
	if in.FieldToMatch != nil {
		in, out := &in.FieldToMatch, &out.FieldToMatch
		*out = make([]FieldToMatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextTransformation != nil {
		in, out := &in.TextTransformation, &out.TextTransformation
		*out = make([]TextTransformationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintStatementParameters.
func (in *SizeConstraintStatementParameters) DeepCopy() *SizeConstraintStatementParameters {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqliMatchStatementObservation) DeepCopyInto(out *SqliMatchStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqliMatchStatementObservation.
func (in *SqliMatchStatementObservation) DeepCopy() *SqliMatchStatementObservation {
	if in == nil {
		return nil
	}
	out := new(SqliMatchStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqliMatchStatementParameters) DeepCopyInto(out *SqliMatchStatementParameters) {
	*out = *in
	if in.FieldToMatch != nil {
		in, out := &in.FieldToMatch, &out.FieldToMatch
		*out = make([]FieldToMatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextTransformation != nil {
		in, out := &in.TextTransformation, &out.TextTransformation
		*out = make([]TextTransformationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqliMatchStatementParameters.
func (in *SqliMatchStatementParameters) DeepCopy() *SqliMatchStatementParameters {
	if in == nil {
		return nil
	}
	out := new(SqliMatchStatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatementObservation) DeepCopyInto(out *StatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatementObservation.
func (in *StatementObservation) DeepCopy() *StatementObservation {
	if in == nil {
		return nil
	}
	out := new(StatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatementParameters) DeepCopyInto(out *StatementParameters) {
	*out = *in
	if in.AndStatement != nil {
		in, out := &in.AndStatement, &out.AndStatement
		*out = make([]AndStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ByteMatchStatement != nil {
		in, out := &in.ByteMatchStatement, &out.ByteMatchStatement
		*out = make([]ByteMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GeoMatchStatement != nil {
		in, out := &in.GeoMatchStatement, &out.GeoMatchStatement
		*out = make([]GeoMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IpSetReferenceStatement != nil {
		in, out := &in.IpSetReferenceStatement, &out.IpSetReferenceStatement
		*out = make([]IpSetReferenceStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedRuleGroupStatement != nil {
		in, out := &in.ManagedRuleGroupStatement, &out.ManagedRuleGroupStatement
		*out = make([]ManagedRuleGroupStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotStatement != nil {
		in, out := &in.NotStatement, &out.NotStatement
		*out = make([]NotStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OrStatement != nil {
		in, out := &in.OrStatement, &out.OrStatement
		*out = make([]OrStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RateBasedStatement != nil {
		in, out := &in.RateBasedStatement, &out.RateBasedStatement
		*out = make([]RateBasedStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegexPatternSetReferenceStatement != nil {
		in, out := &in.RegexPatternSetReferenceStatement, &out.RegexPatternSetReferenceStatement
		*out = make([]RegexPatternSetReferenceStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuleGroupReferenceStatement != nil {
		in, out := &in.RuleGroupReferenceStatement, &out.RuleGroupReferenceStatement
		*out = make([]RuleGroupReferenceStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SizeConstraintStatement != nil {
		in, out := &in.SizeConstraintStatement, &out.SizeConstraintStatement
		*out = make([]SizeConstraintStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SqliMatchStatement != nil {
		in, out := &in.SqliMatchStatement, &out.SqliMatchStatement
		*out = make([]SqliMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.XssMatchStatement != nil {
		in, out := &in.XssMatchStatement, &out.XssMatchStatement
		*out = make([]XssMatchStatementParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatementParameters.
func (in *StatementParameters) DeepCopy() *StatementParameters {
	if in == nil {
		return nil
	}
	out := new(StatementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextTransformationObservation) DeepCopyInto(out *TextTransformationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextTransformationObservation.
func (in *TextTransformationObservation) DeepCopy() *TextTransformationObservation {
	if in == nil {
		return nil
	}
	out := new(TextTransformationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextTransformationParameters) DeepCopyInto(out *TextTransformationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextTransformationParameters.
func (in *TextTransformationParameters) DeepCopy() *TextTransformationParameters {
	if in == nil {
		return nil
	}
	out := new(TextTransformationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UriPathObservation) DeepCopyInto(out *UriPathObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UriPathObservation.
func (in *UriPathObservation) DeepCopy() *UriPathObservation {
	if in == nil {
		return nil
	}
	out := new(UriPathObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UriPathParameters) DeepCopyInto(out *UriPathParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UriPathParameters.
func (in *UriPathParameters) DeepCopy() *UriPathParameters {
	if in == nil {
		return nil
	}
	out := new(UriPathParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisibilityConfigObservation) DeepCopyInto(out *VisibilityConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisibilityConfigObservation.
func (in *VisibilityConfigObservation) DeepCopy() *VisibilityConfigObservation {
	if in == nil {
		return nil
	}
	out := new(VisibilityConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisibilityConfigParameters) DeepCopyInto(out *VisibilityConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisibilityConfigParameters.
func (in *VisibilityConfigParameters) DeepCopy() *VisibilityConfigParameters {
	if in == nil {
		return nil
	}
	out := new(VisibilityConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAcl) DeepCopyInto(out *Wafv2WebAcl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAcl.
func (in *Wafv2WebAcl) DeepCopy() *Wafv2WebAcl {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAcl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wafv2WebAcl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAclList) DeepCopyInto(out *Wafv2WebAclList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Wafv2WebAcl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAclList.
func (in *Wafv2WebAclList) DeepCopy() *Wafv2WebAclList {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAclList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wafv2WebAclList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAclObservation) DeepCopyInto(out *Wafv2WebAclObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAclObservation.
func (in *Wafv2WebAclObservation) DeepCopy() *Wafv2WebAclObservation {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAclObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAclParameters) DeepCopyInto(out *Wafv2WebAclParameters) {
	*out = *in
	if in.DefaultAction != nil {
		in, out := &in.DefaultAction, &out.DefaultAction
		*out = make([]DefaultActionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TagsAll != nil {
		in, out := &in.TagsAll, &out.TagsAll
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VisibilityConfig != nil {
		in, out := &in.VisibilityConfig, &out.VisibilityConfig
		*out = make([]VisibilityConfigParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAclParameters.
func (in *Wafv2WebAclParameters) DeepCopy() *Wafv2WebAclParameters {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAclParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAclSpec) DeepCopyInto(out *Wafv2WebAclSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAclSpec.
func (in *Wafv2WebAclSpec) DeepCopy() *Wafv2WebAclSpec {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAclSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wafv2WebAclStatus) DeepCopyInto(out *Wafv2WebAclStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wafv2WebAclStatus.
func (in *Wafv2WebAclStatus) DeepCopy() *Wafv2WebAclStatus {
	if in == nil {
		return nil
	}
	out := new(Wafv2WebAclStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchStatementObservation) DeepCopyInto(out *XssMatchStatementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchStatementObservation.
func (in *XssMatchStatementObservation) DeepCopy() *XssMatchStatementObservation {
	if in == nil {
		return nil
	}
	out := new(XssMatchStatementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchStatementParameters) DeepCopyInto(out *XssMatchStatementParameters) {
	*out = *in
	if in.FieldToMatch != nil {
		in, out := &in.FieldToMatch, &out.FieldToMatch
		*out = make([]FieldToMatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextTransformation != nil {
		in, out := &in.TextTransformation, &out.TextTransformation
		*out = make([]TextTransformationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchStatementParameters.
func (in *XssMatchStatementParameters) DeepCopy() *XssMatchStatementParameters {
	if in == nil {
		return nil
	}
	out := new(XssMatchStatementParameters)
	in.DeepCopyInto(out)
	return out
}
