// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministrator) DeepCopyInto(out *OrganizationsDelegatedAdministrator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministrator.
func (in *OrganizationsDelegatedAdministrator) DeepCopy() *OrganizationsDelegatedAdministrator {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministrator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationsDelegatedAdministrator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministratorList) DeepCopyInto(out *OrganizationsDelegatedAdministratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrganizationsDelegatedAdministrator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministratorList.
func (in *OrganizationsDelegatedAdministratorList) DeepCopy() *OrganizationsDelegatedAdministratorList {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationsDelegatedAdministratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministratorObservation) DeepCopyInto(out *OrganizationsDelegatedAdministratorObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministratorObservation.
func (in *OrganizationsDelegatedAdministratorObservation) DeepCopy() *OrganizationsDelegatedAdministratorObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministratorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministratorParameters) DeepCopyInto(out *OrganizationsDelegatedAdministratorParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministratorParameters.
func (in *OrganizationsDelegatedAdministratorParameters) DeepCopy() *OrganizationsDelegatedAdministratorParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministratorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministratorSpec) DeepCopyInto(out *OrganizationsDelegatedAdministratorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministratorSpec.
func (in *OrganizationsDelegatedAdministratorSpec) DeepCopy() *OrganizationsDelegatedAdministratorSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationsDelegatedAdministratorStatus) DeepCopyInto(out *OrganizationsDelegatedAdministratorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationsDelegatedAdministratorStatus.
func (in *OrganizationsDelegatedAdministratorStatus) DeepCopy() *OrganizationsDelegatedAdministratorStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationsDelegatedAdministratorStatus)
	in.DeepCopyInto(out)
	return out
}
