// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorder) DeepCopyInto(out *ConfigConfigurationRecorder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorder.
func (in *ConfigConfigurationRecorder) DeepCopy() *ConfigConfigurationRecorder {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigConfigurationRecorder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorderList) DeepCopyInto(out *ConfigConfigurationRecorderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigConfigurationRecorder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorderList.
func (in *ConfigConfigurationRecorderList) DeepCopy() *ConfigConfigurationRecorderList {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigConfigurationRecorderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorderObservation) DeepCopyInto(out *ConfigConfigurationRecorderObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorderObservation.
func (in *ConfigConfigurationRecorderObservation) DeepCopy() *ConfigConfigurationRecorderObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorderParameters) DeepCopyInto(out *ConfigConfigurationRecorderParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RecordingGroup != nil {
		in, out := &in.RecordingGroup, &out.RecordingGroup
		*out = make([]RecordingGroupParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorderParameters.
func (in *ConfigConfigurationRecorderParameters) DeepCopy() *ConfigConfigurationRecorderParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorderSpec) DeepCopyInto(out *ConfigConfigurationRecorderSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorderSpec.
func (in *ConfigConfigurationRecorderSpec) DeepCopy() *ConfigConfigurationRecorderSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfigurationRecorderStatus) DeepCopyInto(out *ConfigConfigurationRecorderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfigurationRecorderStatus.
func (in *ConfigConfigurationRecorderStatus) DeepCopy() *ConfigConfigurationRecorderStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigConfigurationRecorderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordingGroupObservation) DeepCopyInto(out *RecordingGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordingGroupObservation.
func (in *RecordingGroupObservation) DeepCopy() *RecordingGroupObservation {
	if in == nil {
		return nil
	}
	out := new(RecordingGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordingGroupParameters) DeepCopyInto(out *RecordingGroupParameters) {
	*out = *in
	if in.AllSupported != nil {
		in, out := &in.AllSupported, &out.AllSupported
		*out = new(bool)
		**out = **in
	}
	if in.IncludeGlobalResourceTypes != nil {
		in, out := &in.IncludeGlobalResourceTypes, &out.IncludeGlobalResourceTypes
		*out = new(bool)
		**out = **in
	}
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordingGroupParameters.
func (in *RecordingGroupParameters) DeepCopy() *RecordingGroupParameters {
	if in == nil {
		return nil
	}
	out := new(RecordingGroupParameters)
	in.DeepCopyInto(out)
	return out
}
