// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyList) DeepCopyInto(out *AutoscalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoscalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyList.
func (in *AutoscalingPolicyList) DeepCopy() *AutoscalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyObservation) DeepCopyInto(out *AutoscalingPolicyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyObservation.
func (in *AutoscalingPolicyObservation) DeepCopy() *AutoscalingPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyParameters) DeepCopyInto(out *AutoscalingPolicyParameters) {
	*out = *in
	if in.AdjustmentType != nil {
		in, out := &in.AdjustmentType, &out.AdjustmentType
		*out = new(string)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(int64)
		**out = **in
	}
	if in.EstimatedInstanceWarmup != nil {
		in, out := &in.EstimatedInstanceWarmup, &out.EstimatedInstanceWarmup
		*out = new(int64)
		**out = **in
	}
	if in.MetricAggregationType != nil {
		in, out := &in.MetricAggregationType, &out.MetricAggregationType
		*out = new(string)
		**out = **in
	}
	if in.MinAdjustmentMagnitude != nil {
		in, out := &in.MinAdjustmentMagnitude, &out.MinAdjustmentMagnitude
		*out = new(int64)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.PredictiveScalingConfiguration != nil {
		in, out := &in.PredictiveScalingConfiguration, &out.PredictiveScalingConfiguration
		*out = make([]PredictiveScalingConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScalingAdjustment != nil {
		in, out := &in.ScalingAdjustment, &out.ScalingAdjustment
		*out = new(int64)
		**out = **in
	}
	if in.StepAdjustment != nil {
		in, out := &in.StepAdjustment, &out.StepAdjustment
		*out = make([]StepAdjustmentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetTrackingConfiguration != nil {
		in, out := &in.TargetTrackingConfiguration, &out.TargetTrackingConfiguration
		*out = make([]TargetTrackingConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyParameters.
func (in *AutoscalingPolicyParameters) DeepCopy() *AutoscalingPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicySpec) DeepCopyInto(out *AutoscalingPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicySpec.
func (in *AutoscalingPolicySpec) DeepCopy() *AutoscalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyStatus) DeepCopyInto(out *AutoscalingPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyStatus.
func (in *AutoscalingPolicyStatus) DeepCopy() *AutoscalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizedMetricSpecificationObservation) DeepCopyInto(out *CustomizedMetricSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizedMetricSpecificationObservation.
func (in *CustomizedMetricSpecificationObservation) DeepCopy() *CustomizedMetricSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(CustomizedMetricSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizedMetricSpecificationParameters) DeepCopyInto(out *CustomizedMetricSpecificationParameters) {
	*out = *in
	if in.MetricDimension != nil {
		in, out := &in.MetricDimension, &out.MetricDimension
		*out = make([]MetricDimensionParameters, len(*in))
		copy(*out, *in)
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizedMetricSpecificationParameters.
func (in *CustomizedMetricSpecificationParameters) DeepCopy() *CustomizedMetricSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(CustomizedMetricSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDimensionObservation) DeepCopyInto(out *MetricDimensionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDimensionObservation.
func (in *MetricDimensionObservation) DeepCopy() *MetricDimensionObservation {
	if in == nil {
		return nil
	}
	out := new(MetricDimensionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDimensionParameters) DeepCopyInto(out *MetricDimensionParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDimensionParameters.
func (in *MetricDimensionParameters) DeepCopy() *MetricDimensionParameters {
	if in == nil {
		return nil
	}
	out := new(MetricDimensionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpecificationObservation) DeepCopyInto(out *MetricSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpecificationObservation.
func (in *MetricSpecificationObservation) DeepCopy() *MetricSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(MetricSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpecificationParameters) DeepCopyInto(out *MetricSpecificationParameters) {
	*out = *in
	if in.PredefinedLoadMetricSpecification != nil {
		in, out := &in.PredefinedLoadMetricSpecification, &out.PredefinedLoadMetricSpecification
		*out = make([]PredefinedLoadMetricSpecificationParameters, len(*in))
		copy(*out, *in)
	}
	if in.PredefinedMetricPairSpecification != nil {
		in, out := &in.PredefinedMetricPairSpecification, &out.PredefinedMetricPairSpecification
		*out = make([]PredefinedMetricPairSpecificationParameters, len(*in))
		copy(*out, *in)
	}
	if in.PredefinedScalingMetricSpecification != nil {
		in, out := &in.PredefinedScalingMetricSpecification, &out.PredefinedScalingMetricSpecification
		*out = make([]PredefinedScalingMetricSpecificationParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpecificationParameters.
func (in *MetricSpecificationParameters) DeepCopy() *MetricSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(MetricSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedLoadMetricSpecificationObservation) DeepCopyInto(out *PredefinedLoadMetricSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedLoadMetricSpecificationObservation.
func (in *PredefinedLoadMetricSpecificationObservation) DeepCopy() *PredefinedLoadMetricSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(PredefinedLoadMetricSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedLoadMetricSpecificationParameters) DeepCopyInto(out *PredefinedLoadMetricSpecificationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedLoadMetricSpecificationParameters.
func (in *PredefinedLoadMetricSpecificationParameters) DeepCopy() *PredefinedLoadMetricSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedLoadMetricSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedMetricPairSpecificationObservation) DeepCopyInto(out *PredefinedMetricPairSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedMetricPairSpecificationObservation.
func (in *PredefinedMetricPairSpecificationObservation) DeepCopy() *PredefinedMetricPairSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(PredefinedMetricPairSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedMetricPairSpecificationParameters) DeepCopyInto(out *PredefinedMetricPairSpecificationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedMetricPairSpecificationParameters.
func (in *PredefinedMetricPairSpecificationParameters) DeepCopy() *PredefinedMetricPairSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedMetricPairSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedMetricSpecificationObservation) DeepCopyInto(out *PredefinedMetricSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedMetricSpecificationObservation.
func (in *PredefinedMetricSpecificationObservation) DeepCopy() *PredefinedMetricSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(PredefinedMetricSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedMetricSpecificationParameters) DeepCopyInto(out *PredefinedMetricSpecificationParameters) {
	*out = *in
	if in.ResourceLabel != nil {
		in, out := &in.ResourceLabel, &out.ResourceLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedMetricSpecificationParameters.
func (in *PredefinedMetricSpecificationParameters) DeepCopy() *PredefinedMetricSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedMetricSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedScalingMetricSpecificationObservation) DeepCopyInto(out *PredefinedScalingMetricSpecificationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedScalingMetricSpecificationObservation.
func (in *PredefinedScalingMetricSpecificationObservation) DeepCopy() *PredefinedScalingMetricSpecificationObservation {
	if in == nil {
		return nil
	}
	out := new(PredefinedScalingMetricSpecificationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedScalingMetricSpecificationParameters) DeepCopyInto(out *PredefinedScalingMetricSpecificationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedScalingMetricSpecificationParameters.
func (in *PredefinedScalingMetricSpecificationParameters) DeepCopy() *PredefinedScalingMetricSpecificationParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedScalingMetricSpecificationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingConfigurationObservation) DeepCopyInto(out *PredictiveScalingConfigurationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingConfigurationObservation.
func (in *PredictiveScalingConfigurationObservation) DeepCopy() *PredictiveScalingConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingConfigurationParameters) DeepCopyInto(out *PredictiveScalingConfigurationParameters) {
	*out = *in
	if in.MaxCapacityBreachBehavior != nil {
		in, out := &in.MaxCapacityBreachBehavior, &out.MaxCapacityBreachBehavior
		*out = new(string)
		**out = **in
	}
	if in.MaxCapacityBuffer != nil {
		in, out := &in.MaxCapacityBuffer, &out.MaxCapacityBuffer
		*out = new(string)
		**out = **in
	}
	if in.MetricSpecification != nil {
		in, out := &in.MetricSpecification, &out.MetricSpecification
		*out = make([]MetricSpecificationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.SchedulingBufferTime != nil {
		in, out := &in.SchedulingBufferTime, &out.SchedulingBufferTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingConfigurationParameters.
func (in *PredictiveScalingConfigurationParameters) DeepCopy() *PredictiveScalingConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepAdjustmentObservation) DeepCopyInto(out *StepAdjustmentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepAdjustmentObservation.
func (in *StepAdjustmentObservation) DeepCopy() *StepAdjustmentObservation {
	if in == nil {
		return nil
	}
	out := new(StepAdjustmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepAdjustmentParameters) DeepCopyInto(out *StepAdjustmentParameters) {
	*out = *in
	if in.MetricIntervalLowerBound != nil {
		in, out := &in.MetricIntervalLowerBound, &out.MetricIntervalLowerBound
		*out = new(string)
		**out = **in
	}
	if in.MetricIntervalUpperBound != nil {
		in, out := &in.MetricIntervalUpperBound, &out.MetricIntervalUpperBound
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepAdjustmentParameters.
func (in *StepAdjustmentParameters) DeepCopy() *StepAdjustmentParameters {
	if in == nil {
		return nil
	}
	out := new(StepAdjustmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetTrackingConfigurationObservation) DeepCopyInto(out *TargetTrackingConfigurationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetTrackingConfigurationObservation.
func (in *TargetTrackingConfigurationObservation) DeepCopy() *TargetTrackingConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(TargetTrackingConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetTrackingConfigurationParameters) DeepCopyInto(out *TargetTrackingConfigurationParameters) {
	*out = *in
	if in.CustomizedMetricSpecification != nil {
		in, out := &in.CustomizedMetricSpecification, &out.CustomizedMetricSpecification
		*out = make([]CustomizedMetricSpecificationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisableScaleIn != nil {
		in, out := &in.DisableScaleIn, &out.DisableScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.PredefinedMetricSpecification != nil {
		in, out := &in.PredefinedMetricSpecification, &out.PredefinedMetricSpecification
		*out = make([]PredefinedMetricSpecificationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetTrackingConfigurationParameters.
func (in *TargetTrackingConfigurationParameters) DeepCopy() *TargetTrackingConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(TargetTrackingConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}
